daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed after 7 days if no further activity occurs,
  but feel free to re-open a closed issue if needed.
closeComment: false
