language: node_js

node_js:
- '6'
- '8'
- '9'
- '10'

services:
- redis-server

script:
- npm run test:cov || npm run test:cov || npm run test:cov

env:
- CXX=g++-4.8 INSTALL_HIREDIS="yes"
- INSTALL_HIREDIS="no"
- CC_TEST_REPORTER_ID="4cee2f60edbf31acac6ddff823f0b93e2e9882c3e5c55130049e0fd878549f84"

before_script:
- if [ "$INSTALL_HIREDIS" = "yes" ]; then npm install hiredis; fi
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

after_success:
- if [ "$INSTALL_HIREDIS" = "yes" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
