language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"
  - "16"

services:
  - redis-server

script:
  - npm run lint
  - npm run build
  - travis_retry npm run test

env:
  - CC_TEST_REPORTER_ID="4cee2f60edbf31acac6ddff823f0b93e2e9882c3e5c55130049e0fd878549f84"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# Trigger a push build on master/release and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - release
    - /^greenkeeper.*$/

deploy:
  # runs semantic-release on each
  - provider: script
    script: npm ci && npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
      node: "14"
