# Runs ioredis lint, build, and test steps in docker.
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
      - greenkeeper**
  pull_request:
    branches:
      - master
      - v5
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - NODE_VERSION: 12-bullseye
          - NODE_VERSION: 14-bullseye
          - NODE_VERSION: 16-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: bash test/docker/main.sh ${{ matrix.NODE_VERSION }}
  test-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test cluster
        run: bash test-cluster/docker/main.sh
